[package]
name = "pip_wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1"
thiserror = "1.0.65"
serde_json = "1.0.132"
toml = "0.8.19"
indexmap = "2.7.0"
reqwest = { version = "0.10", features = ["blocking", "json"] }
scraper = "0.22.0"
